ci:
  autofix_prs: false
  skip: [mypy]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies:
          - dataclasses-json
          - hydra-core
          - rhoknp==1.7.0
          - cohesion-tools==0.7.3
          - numpy
          - torch
          - torchmetrics
          - tokenizers==0.19.1
          - transformers==4.40.0
          - lightning==2.2.2
        language_version: python3.9
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        files: ^scripts/
        types: [ shell ]
      - id: shfmt
        files: ^scripts/
        types: [ shell ]
        args: [ -i 2 -sr ]
  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.7.1
    hooks:
      - id: validate_manifest
