defaults:
  - _self_

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

data_dir: ${work_dir}/data
save_dir: ${work_dir}/result

# seed for random number generators in pytorch, numpy and python.random
# "null" means the seed is randomly selected at runtime.
seed: null

config_name: ${hydra:job.config_name}
name: ${config_name}${hydra:job.override_dirname}

exp_dir: ${save_dir}/${name}
run_id: ${now:%m%d}_${now:%H%M%S}
run_dir: ${exp_dir}/${run_id}

keys_to_resolve:
  - work_dir
  - data_dir
  - save_dir
  - config_name
  - name
  - exp_dir
  - run_id
  - run_dir

hydra:
  run:
    dir: ${exp_dir}
  sweep:
    dir: result/multirun
    subdir: ${hydra:job.num}
  job:
    config:
      override_dirname:
        kv_sep: '_'
        item_sep: '-'
        exclude_keys:
          - seed
          - name
          - exp_dir
          - run_dir
          - keys_to_resolve
          - devices
          - num_workers
          - logger
          - max_batches_per_device
          - compile
