defaults:
  - train:
      - kwdlc.yaml
      - kc.yaml
      - fuman.yaml
      - wac.yaml
      - jcre3.yaml
  - valid:
      - kwdlc.yaml
      - kc.yaml
      - fuman.yaml
      - wac.yaml
      - jcre3.yaml
  - test:
      - kwdlc.yaml
      - kc.yaml
      - fuman.yaml
      - wac.yaml
      - jcre3.yaml
  - predict:
      - custom.yaml

batch_size: ${max_batches_per_device}
num_workers: ${num_workers}
